name: Verify Ronin Connection and Kubeconfig Secret

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: [self-hosted, linux, ronin, k8s, control-plane]   # Labels must match your Ronin VM runner
    steps:
      - name: Verify runner connection
        run: |
          echo "✅ Connected to runner: $(hostname)"
          echo "Time: $(date)"

      - name: Check if KUBE_CONFIG_B64 secret exists
        run: |
          if [ -z "${{ secrets.KUBE_CONFIG_B64 }}" ]; then
            echo "❌ Secret KUBE_CONFIG_B64 is missing or empty!"
            exit 1
          else
            echo "✅ Secret KUBE_CONFIG_B64 is available (length: $(echo -n "${{ secrets.KUBE_CONFIG_B64 }}" | wc -c) chars)"
          fi

      - name: Decode kubeconfig (safe check)
        run: |
          echo "${{ secrets.KUBE_CONFIG_B64 }}" | base64 -d > kubeconfig.yaml
          head -n 5 kubeconfig.yaml
          echo "✅ Kubeconfig decoded successfully (showing only first 5 lines)"
