name: Deploy Wazuh Agent

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Wazuh Agent image
        run: docker pull ghcr.io/saurab123456/wazuh-agent:4.12.0

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/wazuh-agent \
            wazuh-agent=ghcr.io/saurab123456/wazuh-agent:4.12.0 \
            -n wazuh
