name: Switch API to 10.0.8.70 and Verify

on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on:
      - self-hosted
      - linux
      - X64
      - ronin
      - k8s
      - control-plane
      - vmware
    env:
      KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
      NEW_API: "https://10.0.8.70:6443"
    steps:
      - uses: actions/checkout@v4

      - name: Ensure kubectl and yq
        run: |
          set -euo pipefail
          if ! command -v kubectl >/dev/null 2>&1; then
            VER="$(curl -fsSL https://dl.k8s.io/release/stable.txt)"
            curl -fsSL -o kubectl "https://dl.k8s.io/release/${VER}/bin/linux/amd64/kubectl"
            chmod +x kubectl && sudo mv kubectl /usr/local/bin/
          fi
          if ! command -v yq >/dev/null 2>&1; then
            curl -fsSL -o yq \
              https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            chmod +x yq && sudo mv yq /usr/local/bin/
          fi

      - name: Write kubeconfig from secret
        run: |
          echo "${{ secrets.KUBE_CONFIG_B64 }}" | base64 -d > "$KUBECONFIG"
          chmod 600 "$KUBECONFIG"
          echo "Old server:"; yq '.clusters[].cluster.server' "$KUBECONFIG"

      - name: Patch kubeconfig to new API
        run: |
          yq -i ".clusters[].cluster.server = env(NEW_API)" "$KUBECONFIG"
          echo "New server:"; yq '.clusters[].cluster.server' "$KUBECONFIG"

      - name: Verify cluster connectivity
        run: |
          kubectl cluster-info
          kubectl get nodes -o wide
