name: Test Runner

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check:
    runs-on: [self-hosted, linux, ronin, k8s, control-plane]

    steps:
      - name: Show runner details
        run: |
          echo "Runner host: $(hostname)"
          echo "Time: $(date)"

      - name: Check Kubernetes cluster
        run: |
          kubectl cluster-info
          kubectl get nodes -o wide
