name: Test Runner

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check:
    runs-on: [self-hosted, linux, ronin, k8s, control-plane]
    steps:
      - name: Identify runner + host
        run: |
          echo "RUNNER_NAME=$RUNNER_NAME"
          echo "RUNNER_OS=$RUNNER_OS  RUNNER_ARCH=$RUNNER_ARCH"
          echo "Hostname: $(hostname)"
          echo "Hostnamectl:"
          hostnamectl || true
          echo "Whoami: $(whoami)"
          echo "IPs:"
          ip -brief addr || ifconfig || true
          echo "Kube context:"
          kubectl config current-context || true

      - name: Prove local file system (create marker)
        run: |
          MARK="/tmp/gha-proof-${GITHUB_REPOSITORY////_}-${GITHUB_RUN_ID}"
          echo "Created at $(date)" | sudo tee "$MARK"
          echo "Marker path: $MARK"
          ls -l "$MARK"
