name: 01) Deploy Wazuh (Core Only - Master + Worker)

on:
  workflow_dispatch:
    inputs:
      wazuh_tag:
        description: "wazuh-kubernetes repo tag (e.g., v4.12.0)"
        required: true
        default: "v4.12.0"
      local_forward_port:
        description: "Local port for port-forward"
        required: true
        default: "8444"
      enable_port_forward:
        description: "Start port-forward automatically (true/false)"
        required: true
        default: "true"

jobs:
  deploy:
    runs-on: [self-hosted, linux, ronin, k8s, control-plane]
    timeout-minutes: 90

    env:
      NS: wazuh
      WAZUH_K8S_TAG: ${{ inputs.wazuh_tag }}
      LOCAL_FORWARD_PORT: ${{ inputs.local_forward_port }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install CLIs (no sudo) - kubectl/yq/jq to $HOME/bin
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$HOME/bin"
          echo "$HOME/bin" >> "$GITHUB_PATH"
          export PATH="$HOME/bin:$PATH"
          if ! command -v kubectl >/dev/null 2>&1; then
            KVER="$(curl -sS https://dl.k8s.io/release/stable.txt)"
            curl -sSL "https://dl.k8s.io/release/${KVER}/bin/linux/amd64/kubectl" -o "$HOME/bin/kubectl"
            chmod +x "$HOME/bin/kubectl"
          fi
          if ! command -v yq >/dev/null 2>&1; then
            curl -sSL -o "$HOME/bin/yq" https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
            chmod +x "$HOME/bin/yq"
          fi
          if ! command -v jq >/dev/null 2>&1; then
            curl -sSL -o "$HOME/bin/jq" https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64
            chmod +x "$HOME/bin/jq"
          fi

      - name: Ensure namespace
        shell: bash
        run: |
          kubectl create namespace "$NS" --dry-run=client -o yaml | kubectl apply -f -

      # Required for OpenSearch (indexer)
      - name: Ensure vm.max_map_count via DaemonSet
        shell: bash
        run: |
          set -euo pipefail
          cat > /tmp/wazuh-sysctl-ds.yaml <<'YAML'
          apiVersion: apps/v1
          kind: DaemonSet
          metadata:
            name: wazuh-sysctl
            namespace: kube-system
            labels: { app: wazuh-sysctl }
          spec:
            selector: { matchLabels: { app: wazuh-sysctl } }
            template:
              metadata: { labels: { app: wazuh-sysctl } }
              spec:
                hostPID: true
                tolerations: [ {operator: "Exists"} ]
                containers:
                  - name: sysctl
                    image: busybox:1.36
                    securityContext: { privileged: true }
                    command: ["/bin/sh","-c"]
                    args:
                      - |
                        set -e
                        echo 262144 > /host-proc/sys/vm/max_map_count
                        mkdir -p /host-etc/sysctl.d
                        echo "vm.max_map_count=262144" > /host-etc/sysctl.d/99-wazuh.conf
                        sleep 3600
                    volumeMounts:
                      - { name: host-proc, mountPath: /host-proc }
                      - { name: host-etc,  mountPath: /host-etc  }
                volumes:
                  - { name: host-proc, hostPath: { path: /proc, type: Directory } }
                  - { name: host-etc,  hostPath: { path: /etc,  type: Directory } }
          YAML
          kubectl apply -f /tmp/wazuh-sysctl-ds.yaml

      - name: Fetch official wazuh-kubernetes repo
        shell: bash
        run: |
          set -e
          rm -rf wazuh-kubernetes
          git clone --depth 1 --branch "$WAZUH_K8S_TAG" https://github.com/wazuh/wazuh-kubernetes.git

      # Kustomize expects certs at wazuh/certs/**
      - name: Generate self-signed certs (indexer + dashboard)
        shell: bash
        run: |
          set -euo pipefail
          CERTROOT="${{ github.workspace }}/wazuh-kubernetes/wazuh/certs"
          IC="${CERTROOT}/indexer_cluster"
          DH="${CERTROOT}/dashboard_http"
          mkdir -p "$IC" "$DH"

          cat > /tmp/wazuh-openssl.cnf <<'CONF'
          [req]
          default_bits=2048
          prompt=no
          default_md=sha256
          req_extensions=v3_req
          distinguished_name=req_dn
          [req_dn]
          CN=wazuh-local
          [v3_req]
          basicConstraints=CA:FALSE
          keyUsage=digitalSignature,keyEncipherment
          extendedKeyUsage=serverAuth,clientAuth
          subjectAltName=@alt_names
          [alt_names]
          DNS.1=wazuh-indexer
          DNS.2=wazuh-indexer.wazuh.svc
          DNS.3=wazuh-dashboard
          DNS.4=wazuh-dashboard.wazuh.svc
          DNS.5=localhost
          IP.1=127.0.0.1
          CONF

          # CA
          openssl genrsa -out "$IC/root-ca-key.pem" 4096
          openssl req -x509 -new -key "$IC/root-ca-key.pem" -sha256 -days 3650 -out "$IC/root-ca.pem" -subj "/CN=Wazuh Root CA"

          sign_cert () {
            local name="$1"
            openssl genrsa -out "$IC/${name}-key.pem" 2048
            openssl req -new -key "$IC/${name}-key.pem" -out "$IC/${name}.csr" -config /tmp/wazuh-openssl.cnf
            openssl x509 -req -in "$IC/${name}.csr" -CA "$IC/root-ca.pem" -CAkey "$IC/root-ca-key.pem" -CAcreateserial \
              -out "$IC/${name}.pem" -days 825 -sha256 -extensions v3_req -extfile /tmp/wazuh-openssl.cnf
            rm -f "$IC/${name}.csr"
          }
          for n in admin node dashboard filebeat; do sign_cert "$n"; done

          openssl genrsa -out "$DH/key.pem" 2048
          openssl req -new -key "$DH/key.pem" -out "$DH/dashboard.csr" -config /tmp/wazuh-openssl.cnf
          openssl x509 -req -in "$DH/dashboard.csr" -CA "$IC/root-ca.pem" -CAkey "$IC/root-ca-key.pem" -CAcreateserial \
            -out "$DH/cert.pem" -days 825 -sha256 -extensions v3_req -extfile /tmp/wazuh-openssl.cnf
          rm -f "$DH/dashboard.csr"

      # Build overlay (core only), filter out StorageClass; no yq 'if' mutations
      - name: Build overlay (core only; no StorageClass)
        shell: bash
        run: |
          set -e
          kubectl kustomize "wazuh-kubernetes/wazuh" > /tmp/wazuh-all.yaml
          # Never apply StorageClass objects from upstream
          yq e 'select(.kind != "StorageClass")' /tmp/wazuh-all.yaml > /tmp/_base.yaml
          # Split for apply
          yq -o=y e 'select(.kind != "StatefulSet")' /tmp/_base.yaml > /tmp/non-sts.yaml
          yq -o=y e 'select(.kind == "StatefulSet")' /tmp/_base.yaml > /tmp/sts.yaml
          # Avoid dashboard replace conflicts when re-running
          kubectl -n "$NS" delete deploy wazuh-dashboard --ignore-not-found=true

      - name: Apply non-StatefulSet resources
        shell: bash
        run: |
          set -e
          if [ -s /tmp/non-sts.yaml ]; then kubectl -n "$NS" apply -f /tmp/non-sts.yaml; fi

      - name: Recreate core StatefulSets and apply
        shell: bash
        run: |
          set -e
          for n in wazuh-manager-master wazuh-manager-worker wazuh-indexer; do
            kubectl -n "$NS" delete statefulset "$n" --ignore-not-found=true
          done
          kubectl -n "$NS" apply -f /tmp/sts.yaml

      # Guardrails: set image and replicas via kubectl (no risky YAML mutations)
      - name: Enforce wazuh-indexer image+replicas and worker replicas
        shell: bash
        run: |
          set -euo pipefail
          TAG_NO_V="${WAZUH_K8S_TAG#v}"
          kubectl -n "$NS" get sts wazuh-indexer >/dev/null 2>&1 || { echo "::error::Missing StatefulSet wazuh-indexer"; exit 1; }
          kubectl -n "$NS" set image statefulset/wazuh-indexer wazuh-indexer=wazuh/wazuh-indexer:${TAG_NO_V}
          kubectl -n "$NS" scale statefulset/wazuh-indexer --replicas=1
          kubectl -n
