name: CI on Ronin

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux, ronin]   # must match labels you set
    timeout-minutes: 60
    env:
      KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write kubeconfig
        if: secrets.KUBECONFIG != ''
        shell: bash
        run: |
          # If you stored raw kubeconfig in the secret:
          printf '%s' "${{ secrets.KUBECONFIG }}" > "$KUBECONFIG"
          chmod 600 "$KUBECONFIG"

      - name: Ensure kubectl (no sudo)
        shell: bash
        run: |
          mkdir -p "$HOME/.local/bin"
          if ! command -v kubectl >/dev/null 2>&1; then
            curl -fsSLo "$HOME/.local/bin/kubectl" "https://dl.k8s.io/release/$(curl -fsSL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x "$HOME/.local/bin/kubectl"
            echo "$HOME/.local/bin" >> $GITHUB_PATH
          fi

      - name: Sanity check cluster
        run: kubectl get nodes -o wide

      - name: Your deploy step
        run: |
          # e.g., kubectl apply -k k8s/overlays/single
          echo "Do deploy here"
